### ISSUE TITLE
add `exit` keyword

### ISSUE THREAD

**Issue by tsujp** [ThakeeNathees/pocketlang#122]
Similar to Ruby having an `exit` keyboard would be nice. I don't think we should bring over the lack of cleanup bang variant `exit!` though.

I'd be happy to implement this if some pointers (pun?) were given.

**Comment by ThakeeNathees** [comment]
You've just opened the issue as I'm thinking about the `exit()` function (like python). It would be great if you could implement it, Soon I'll open an issue with `pointer[]` (pun? pointers)

**Comment by tsujp** [comment]
So the intention is to have this be a function and not a keyword? I think it'd make sense as a keyword personally give the Ruby-like nature of the syntax -- there's also Python inspiration here too right.

Any tips on where to start? I saw some keyword definitions if that approach is a thing else if you're steadfast on `exit()` instead of `exit` I can grep around for special function names.

**Comment by ThakeeNathees** [comment]
All the built-in functions are defined at `src/pk_core.c` where you could add an `exit()` function that'll take an optional number as an exit code, and for now just use C's `void exit(int status)` function to terminate.

Instead of C's `exit()` we need to set the VM's fiber to `NULL` this will make the VM return from the execution but we need some way to set an exit code properly (I'll add this to my TODOs).

**Comment by tsujp** [comment]
I'll have a go at this tomorrow my time, for now... bed.

**Comment by tsujp** [comment]
PR: https://github.com/ThakeeNathees/pocketlang/pull/138
