### ISSUE TITLE
include lua benchmarks

### ISSUE THREAD

**Issue by lukeed** [ThakeeNathees/pocketlang#132]
Similar to #124 – I have the the benchmarks converted into Lua, which is more of a direct point of comparison than Node.js is.

Can PR if you'd like :) With performance in mind, I think it'd be a really good language to measure & compare against.

**Comment by ThakeeNathees** [comment]
That would be a better language to compare, than node (just for the records, lua is register based VM which makes it more faster than stack based) since it's similar to pocketlang (small and embeddable). But we'll keep the node js around.

And Yeah, open the PR, I've cleaned and refactored the benchmark script to autodetect installed interpreters #134 where you can add lua too.

**Comment by ThakeeNathees** [comment]
@lukeed Just wanna say thanks to making all those benchmarks 🎉

**Comment by lukeed** [comment]
You're welcome :)
